<a href="https://colab.research.google.com/github/404isabel/03MAIR-Algoritmos-de-optimizacion/blob/master/Utilidades/Backtraking_reinas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
tablero=np.zeros((4,4))
print(tablero)

def tableroReinas(tablero,x,y,iteracion):
 
  total=tablero==1  
  maskx=tablero[x]==1
 
  existeY=False
  i=0
  while(i<len(tablero-1) and existeY==False):
    if(tablero[i][y]==1):
      existeY=True
    i=i+1
  
 
  if(len(tablero[maskx])==0 and existeY==False):    
   
    tablero[x][y]=1  
    #Hago salto de caballo
    indicex=x
    if(x<len(tablero)-1):
      indicex=x+1
    if(y+2>len(tablero)-1):
      indicey=0
    else:
      indicey=y+2
      
    tableroReinas(tablero,indicex,indicey,iteracion)
  
  #El algoritmo ha fracasado, vuelvo a empezar
  elif(len(tablero[total])<len(tablero) and iteracion<3):     
    tablero[::]=0
    tableroReinas(tablero,0,iteracion+1,iteracion+1)
  
tableroReinas(tablero,0,0,0)
print('\r\n Tablero con reinas: \r\n')
print(tablero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 Tablero con reinas 

[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]]
