<a href="https://colab.research.google.com/github/404isabel/03MAIR-Algoritmos-de-optimizacion/blob/master/Utilidades/Ordenacion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from time import time
milista = [9187, 244, 4054, 9222, 8373, 4993, 5265, 5470, 4519, 7182, 2035, 3506, 4337, 7580, 2554, 2824, 8357, 4447, 7379]


#Ordenación por burbuja
@calcular_tiempo
def bubble_sort(A):
  for i in range(len(A)-1):
    for j in range(len(A)-1):
      if(A[j]>A[j+1]):      
        A[j], A[j+1] = A[j+1], A[j]
        
  print(A) 

bubble_sort(milista)


A = [9187, 244, 4054, 9222, 8373, 4993, 5265, 5470, 4519, 7182, 2035, 3506, 4337, 7580, 2554, 2824, 8357, 4447, 7379]
#Ordenación por montículos
@calcular_tiempo
class MonticuloBinario:
    def __init__(self):
        self.listaMonticulo = [0]
        self.tamanoActual = 0


    def infiltArriba(self,i):
        while i // 2 > 0:
          if self.listaMonticulo[i] < self.listaMonticulo[i // 2]:
             tmp = self.listaMonticulo[i // 2]
             self.listaMonticulo[i // 2] = self.listaMonticulo[i]
             self.listaMonticulo[i] = tmp
          i = i // 2

    def insertar(self,k):
      self.listaMonticulo.append(k)
      self.tamanoActual = self.tamanoActual + 1
      self.infiltArriba(self.tamanoActual)

    def infiltAbajo(self,i):
      while (i * 2) <= self.tamanoActual:
          hm = self.hijoMin(i)
          if self.listaMonticulo[i] > self.listaMonticulo[hm]:
              tmp = self.listaMonticulo[i]
              self.listaMonticulo[i] = self.listaMonticulo[hm]
              self.listaMonticulo[hm] = tmp
          i = hm

    def hijoMin(self,i):
      if i * 2 + 1 > self.tamanoActual:
          return i * 2
      else:
          if self.listaMonticulo[i*2] < self.listaMonticulo[i*2+1]:
              return i * 2
          else:
              return i * 2 + 1

    def eliminarMin(self):
      valorSacado = self.listaMonticulo[1]
      self.listaMonticulo[1] = self.listaMonticulo[self.tamanoActual]
      self.tamanoActual = self.tamanoActual - 1
      self.listaMonticulo.pop()
      self.infiltAbajo(1)
      return valorSacado

    def construirMonticulo(self,unaLista):
      i = len(unaLista) // 2
      self.tamanoActual = len(unaLista)
      self.listaMonticulo = [0] + unaLista[:]
      while (i > 0):
          self.infiltAbajo(i)
          i = i - 1

  

miMonticulo = MonticuloBinario()
miMonticulo.construirMonticulo(A)
for t in range(len(A)):
  print(miMonticulo.eliminarMin())

  

[244, 2035, 2554, 2824, 3506, 4054, 4337, 4447, 4519, 4993, 5265, 5470, 7182, 7379, 7580, 8357, 8373, 9187, 9222]
Tiempo de ejecución para algoritmo: 0.0006620883941650391
Tiempo de ejecución para algoritmo: 1.9073486328125e-06
244
2035
2554
2824
3506
4054
4337
4447
4519
4993
5265
5470
7182
7379
7580
8357
8373
9187
9222


In [0]:
#Divide y vencerás
#N:número que hay que resolver
#desde: posición donde se encuentra la torre que hay que resolver
#hasta: posición hasta la cual movemos
def torres_hanoy(N, desde, hasta):
  #print("entro en la función "+str(N)+" "+str(desde)+ "  "+str(hasta))
  if(N==1):
    print("Desde "+str(desde)+ " hasta "+str(hasta))
  else:
    torres_hanoy(N-1, desde, 6-desde-hasta)
    print("Desde "+str(desde)+ " hasta "+str(hasta))
    torres_hanoy(N-1, 6-desde-hasta,hasta)
    
torres_hanoy(3,1,3)


Desde 1 hasta 3
Desde 1 hasta 2
Desde 3 hasta 2
Desde 1 hasta 3
Desde 2 hasta 1
Desde 2 hasta 3
Desde 1 hasta 3


In [0]:
import numpy as np

In [0]:
tablero=np.zeros((5,5))
tablero

def tableroReinas(tablero,x,y,iteracion):
 
  total=tablero==1  
  maskx=tablero[x]==1
 
  existeY=False
  i=0
  while(i<len(tablero-1) and existeY==False):
    if(tablero[i][y]==1):
      existeY=True
    i=i+1
  
 
  if(len(tablero[maskx])==0 and existeY==False):    
   
    tablero[x][y]=1  
    #Hago salto de caballo
    indicex=x
    if(x<len(tablero)-1):
      indicex=x+1
    if(y+2>len(tablero)-1):
      indicey=0
    else:
      indicey=y+2
      
    tableroReinas(tablero,indicex,indicey,iteracion)
  
  #El algoritmo ha fracasado, vuelvo a empezar
  elif(len(tablero[total])<len(tablero) and iteracion<3):     
    tablero[::]=0
    tableroReinas(tablero,0,iteracion+1,iteracion+1)
  
tableroReinas(tablero,0,0,0)
print('\r\n')
print(tablero)







[[0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]]


In [1]:
# Ordenación por selección

def selectionSort(alist):
  for fillslot in range(len(alist)-1,0,-1):
    positionOfMax=0
    for location in range(1,fillslot+1):
      if alist[location]>alist[positionOfMax]:
        positionOfMax = location
    temp = alist[fillslot]
    alist[fillslot] = alist[positionOfMax]
    alist[positionOfMax] = temp
    
alist = [54,26,93,17,77,31,44,55,20]
selectionSort(alist)
print(alist)

[17, 20, 26, 31, 44, 54, 55, 77, 93]


In [2]:
# Ordenación por mezcla


def mergeSort(alist):
  print("Splitting ",alist)
  if len(alist)>1:
    mid = len(alist)//2
    lefthalf = alist[:mid]
    righthalf = alist[mid:]
    mergeSort(lefthalf)
    mergeSort(righthalf)
    i=0
    j=0
    k=0
    while i < len(lefthalf) and j < len(righthalf):
      if lefthalf[i] < righthalf[j]:
        alist[k]=lefthalf[i]
        i=i+1
      else:
        alist[k]=righthalf[j]
        j=j+1
      k=k+1
    while i < len(lefthalf):
      alist[k]=lefthalf[i]
      i=i+1
      k=k+1
    while j < len(righthalf):
      alist[k]=righthalf[j]
      j=j+1
      k=k+1
  print("Merging ",alist)
alist = [54,26,93,17,77,31,44,55,20]
mergeSort(alist)
print(alist)

Splitting  [54, 26, 93, 17, 77, 31, 44, 55, 20]
Splitting  [54, 26, 93, 17]
Splitting  [54, 26]
Splitting  [54]
Merging  [54]
Splitting  [26]
Merging  [26]
Merging  [26, 54]
Splitting  [93, 17]
Splitting  [93]
Merging  [93]
Splitting  [17]
Merging  [17]
Merging  [17, 93]
Merging  [17, 26, 54, 93]
Splitting  [77, 31, 44, 55, 20]
Splitting  [77, 31]
Splitting  [77]
Merging  [77]
Splitting  [31]
Merging  [31]
Merging  [31, 77]
Splitting  [44, 55, 20]
Splitting  [44]
Merging  [44]
Splitting  [55, 20]
Splitting  [55]
Merging  [55]
Splitting  [20]
Merging  [20]
Merging  [20, 55]
Merging  [20, 44, 55]
Merging  [20, 31, 44, 55, 77]
Merging  [17, 20, 26, 31, 44, 54, 55, 77, 93]
[17, 20, 26, 31, 44, 54, 55, 77, 93]
